#!/usr/bin/env bash
# Open the /etc/passwd file for reading
while IFS=: read -r username password user_id group_id user_info home_directory shell
do
	    # Check if the fields are correctly populated
	        if [[ -n "$username" && -n "$user_id" && -n "$group_id" && -n "$home_directory" && -n "$shell" ]]; then
			        echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
				    fi
			    done < /etc/passwd

