#!/usr/bin/env bash
# Use awk to parse the log file, group by IP and HTTP code, and count occurrences
awk '{print $1, $9}' apache-access.log | 
	    awk '{count[$1,$2]++} END {for (i in count) print count[i], i}' |
	        sort -rn

