#!/usr/bin/env bash
# Use awk to process the log file, grouping by IP and HTTP status code
awk '{count[$1, $9]++} END {for (key in count) {split(key, arr, SUBSEP); print count[key], arr[1], arr[2]}}' apache-access.log | sort -rn

